#!/bin/bash

DISPLAY_NAME="rstudio-server"
# grab the username
source /etc/profile.d/0000-env.sh
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst)
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export GROUP_NAME" | envsubst)

chown -R ${USER_NAME}:${GROUP_NAME} /var/lib/rstudio-server
chmod -R g=u /var/lib/rstudio-server
mkdir -p /var/run/rstudio-server
chmod 1777 /var/run/rstudio-server

# rstudio server uses an 'auth-none' flag to disable auth
if [[ ${AUTH} == 'none' ]] ; then
    RSTUDIO_SERVER_AUTH_NONE="1"
else
    RSTUDIO_SERVER_AUTH_NONE=""
fi

export RSTUDIO_SERVER_ADDR=${RSTUDIO_SERVER_ADDR:='0.0.0.0'}
export RSTUDIO_SERVER_PORT=${RSTUDIO_SERVER_PORT:='8787'}

COMMAND_ARGS=\
${RSTUDIO_SERVER_ADDR:+"      --www-address   ${RSTUDIO_SERVER_ADDR}            "}\
${RSTUDIO_SERVER_PORT:+"      --www-port      ${RSTUDIO_SERVER_PORT}            "}\
${RSTUDIO_SERVER_AUTH_NONE:+" --auth-none     ${RSTUDIO_SERVER_AUTH_NONE}       "}\
${USER_NAME:+"                --server-user   ${USER_NAME}                      "}\
${USER_NAME:+"                --server-working-dir "'${HOME}'"                  "}

COMMAND=" /usr/lib/rstudio-server/bin/rserver --server-daemonize=0 $(echo -n ${COMMAND_ARGS} ) "

su - ${USER_NAME} -c "{
  echo [\"$(date +%Y-%m-%dT%H:%M:%S%z)\"] info s6-${DISPLAY_NAME}' user:     '"'$(id)'" \
; echo [\"$(date +%Y-%m-%dT%H:%M:%S%z)\"] info s6-${DISPLAY_NAME}' command: '\"${COMMAND}\" \
; ${COMMAND} \
; }"
