#!/bin/bash

# grab the username
source /etc/profile.d/0000-env.sh
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst)

export CODE_SERVER_AUTH=${AUTH:-none}
export CODE_SERVER_DISABLE_TELEMETRY=${CODE_SERVER_DISABLE_TELEMETRY:=true}
export CODE_SERVER_DISABLE_UPDATE_CHECK=${CODE_SERVER_DISABLE_UPDATE_CHECK:=true}
export CODE_SERVER_BIND_ADDR=${CODE_SERVER_BIND_ADDR:='0.0.0.0:8080'}

CODE_SERVER_CLI_ARGS=\
${CODE_SERVER_AUTH:+"                 --auth                 ${CODE_SERVER_AUTH}                 "}\
${CODE_SERVER_CERT:+"                 --cert                 ${CODE_SERVER_CERT}                 "}\
${CODE_SERVER_CERT_HOST:+"            --cert-host            ${CODE_SERVER_CERT_HOST}            "}\
${CODE_SERVER_CERT_KEY:+"             --cert-key             ${CODE_SERVER_CERT_KEY}             "}\
${CODE_SERVER_DISABLE_TELEMETRY:+"    --disable-telemetry                                        "}\
${CODE_SERVER_DISABLE_UPDATE_CHECK:+" --disable-update-check                                     "}\
${CODE_SERVER_BIND_ADDR:+"            --bind-addr            ${CODE_SERVER_BIND_ADDR}            "}\
${CODE_SERVER_CONFIG:+"               --config               ${CODE_SERVER_CONFIG}               "}\
${CODE_SERVER_SOCKET:+"               --socket               ${CODE_SERVER_SOCKET}               "}\
${CODE_SERVER_USER_DATA_DIR:+"        --user-data-dir        ${CODE_SERVER_USER_DATA_DIR}        "}\
${CODE_SERVER_EXTENSIONS_DIR:+"       --extensions-dir       ${CODE_SERVER_EXTENSIONS_DIR}       "}\
${CODE_SERVER_ENABLE_PROPOSED_API:+"  --enable-proposed-api  ${CODE_SERVER_ENABLE_PROPOSED_API}  "}\
${CODE_SERVER_PROXY_DOMAIN:+"         --proxy-domain         ${CODE_SERVER_PROXY_DOMAIN}         "}\
${CODE_SERVER_LINK:+"                 --link                 ${CODE_SERVER_LINK}                 "}

echo "-----------------------------------------------------------"
echo "code-server:"
echo "User: ${USER_NAME:=liveware}"
su - ${USER_NAME} -c 'id'
echo "Command:"
su - ${USER_NAME} -c "echo /usr/local/bin/code-server ${CODE_SERVER_CLI_ARGS} "'${HOME}'
echo "-----------------------------------------------------------"
su - ${USER_NAME} -c '/usr/local/bin/code-server '"${CODE_SERVER_CLI_ARGS}"'${HOME}'


