#!/bin/bash

# grab the username
source /etc/profile.d/0000-env.sh
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst)

chown -R ${USER_NAME}:${GROUP_NAME} /var/log/pgadmin
chmod -R g=u /var/lib/rstudio-server

# TODO: AUTH: none, oidc, password
# use caddy as the auth gatekeeper:
# none: PAM password created but not required for anything
# oidc: use oidc
# password: use PAM

CADDY_SERVER_CONFIG=${CADDY_SERVER_CONFIG:='/etc/caddy/Caddyfile'}

# build the command to run
CADDY_SERVER_CLI_ARGS=${CADD_SERVER_CLI_ARGS:=" --config ${CADDY_SERVER_CONFIG} "}

CADDY_SERVER_CLI_CMD=${CADDY_SERVER_CLI_CMD:=" $(which caddy) run ${CADDY_SERVER_CLI_ARGS}" }

{
    echo "----------------------------------------------------------------------"
    echo "Caddy Server"
    echo "--------------------"
    su - ${USER_NAME} -c 'echo "User: $(id)" '
    echo "Command:"
    su - ${USER_NAME} -c "echo ${CADDY_SERVER_CLI_CMD}"
    echo "--------------------"
    su - ${USER_NAME} -c "${CADDY_SERVER_CLI_CMD}"
    echo "----------------------------------------------------------------------"
}
