#!/bin/bash

# grab the username
source /etc/profile.d/0000-env.sh
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst)

chown -R ${USER_NAME}:${GROUP_NAME} /var/log/pgadmin
chmod -R g=u /var/lib/rstudio-server

# TODO: AUTH: none, oidc, password
# use caddy as the auth gatekeeper:
# none: PAM password created but not required for anything
# oidc: use oidc
# password: use PAM

CADDY_SERVER_CONFIG=${CADDY_SERVER_CONFIG:='/etc/caddy/Caddyfile'}

# build the command to run
CADDY_SERVER_CLI_ARGS=${CADD_SERVER_CLI_ARGS:=" --config ${CADDY_SERVER_CONFIG} --watch "}
CADDY_SERVER_CLI_CMD=${CADDY_SERVER_CLI_CMD:=" $(which caddy) run ${CADDY_SERVER_CLI_ARGS}" }

su - ${USER_NAME} -c "{
echo '---------------------------------------------------------------------' \
&& echo 'Caddy User: $(id)' \
&& echo 'Caddy Command: '${CADDY_SERVER_CLI_CMD} \
&& ${CADDY_SERVER_CLI_CMD} \
&& echo '---------------------------------------------------------------------' \
; }"

# {
#     "----------------------------------------------------------------------"
#     su - ${USER_NAME} -c 'echo "Caddy User: $(id)" '
#     su - ${USER_NAME} -c "echo 'Caddy Command: '${CADDY_SERVER_CLI_CMD}"
#     su - ${USER_NAME} -c "${CADDY_SERVER_CLI_CMD}"
#     "----------------------------------------------------------------------"
# }