#!/bin/bash

DISPLAY_NAME="label-studio"
# grab the username
source /etc/profile.d/0000-env.sh
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst)
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export GROUP_NAME" | envsubst)
user_xdg_data_home=$(su - ${USER_NAME} -c 'echo $XDG_DATA_HOME')
user_xdg_config_home=$(su - ${USER_NAME} -c 'echo $XDG_CONFIG_HOME')
user_home=$(su - ${USER_NAME} -c 'echo $HOME')

COMMAND_ENV="
export LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME:=${USER_NAME}"@localhost.com"} \
export LABEL_STUDIO_PASSWORD=${PASSWORD} \
export LABEL_STUDIO_PORT=${LABEL_STUDIO_PORT:=13500} \
export LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:=http://localhost/label-studio} \
export LABEL_STUDIO_BASE_DATA_DIR=${user_xdg_data_home} \
export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=${LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED:=true} \
export LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=${user_home} \
"

# LABEL_STUDIO_DATABASE
# DJANGO_DB=default
# POSTGRE_NAME=postgres
# POSTGRE_USER=postgres
# POSTGRE_PASSWORD=
# POSTGRE_PORT=5432
# POSTGRE_HOST=db

# build the command to run
COMMAND_ARGS=${LABEL_STUDIO_COMMAND_ARGS}
COMMAND=$(echo "${COMMAND_ENV} && cd /opt/label-studio && source bin/activate && label-studio ${COMMAND_ARGS} ")
echo ${COMMAND}

su - ${USER_NAME} -c "{
  echo [\"$(date +%Y-%m-%dT%H:%M:%S%z)\"] info s6-${DISPLAY_NAME}' user:     '"'$(id)'" \
; echo [\"$(date +%Y-%m-%dT%H:%M:%S%z)\"] info s6-${DISPLAY_NAME}' command: '\"${COMMAND}\" \
; ${COMMAND} \
; }"

