#!/bin/bash

DISPLAY_NAME="label-studio"
# grab the username
source /etc/profile.d/0000-env.sh
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst)
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export GROUP_NAME" | envsubst)
user_xdg_data_home=$(su - ${USER_NAME} -c 'echo $XDG_DATA_HOME')
user_xdg_config_home=$(su - ${USER_NAME} -c 'echo $XDG_CONFIG_HOME')
user_home=$(su - ${USER_NAME} -c 'echo $HOME')

COMMAND_ENV="
export LABEL_STUDIO_USERNAME=${USER_NAME}
export LABEL_STUDIO_PASSWORD=${PASSWORD}
export LABEL_STUDIO_PORT=${LABEL_STUDIO_PORT:=13500}
export LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:=localhost}
export LABEL_STUDIO_BASE_DATA_DIR=${user_xdg_data_home}
export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=${LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED:=true}
export LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=${user_home}
export LABEL_STUDIO_PORT=10000
"

# LABEL_STUDIO_DATABASE
# DJANGO_DB=default
# POSTGRE_NAME=postgres
# POSTGRE_USER=postgres
# POSTGRE_PASSWORD=
# POSTGRE_PORT=5432
# POSTGRE_HOST=db
# 

# build the command to runS
COMMAND_ARGS=${CADD_SERVER_CLI_ARGS:=" --config ${CADDY_SERVER_CONFIG} --watch "}
COMMAND=$(echo "${COMMAND_ENV} && cd /opt/label-studio && source bin/activate && label-studio ${COMMAND_ARGS} ")

echo ${DISPLAY_NAME}' User: $(id)' 
echo " Command: ${COMMAND}" 
${COMMAND}


su - ${USER_NAME} -c "{
export CB_SERVER_NAME=${CB_SERVER_NAME} \
&& export CB_SERVER_URL=${CB_SERVER_URL} \
&& export CB_ADMIN_NAME=${CB_ADMIN_NAME} \
&& export CB_ADMIN_PASSWORD=${CB_ADMIN_PASSWORD} \
&& echo '---------------------------------------------------------------------' \
&& echo 'CloudBeaver User: $(id)' \
&& echo 'Cloudbeaver Command: '\"${CB_CLI_COMMAND}\" \
&& ${CB_CLI_COMMAND} \
&& echo '---------------------------------------------------------------------' \
; }"


python -m venv /opt/label-studio && source /opt/label-studio/bin/activate
pip install --upgrade pip
pip install --upgrade label-studio
source /opt/label-studio/bin/activate
label-studio \
--password=password \
--username=liveware@localhost.com 

rm -rf ~/.local/share/label-studio
rm -rf ~/.config/label-studio
label-studio --password=password --username=liveware@localhost.com --host=http://example/label-studio
label-studio --password=password --username=liveware@localhost.com --host=http://localhost/label-studio --port=13500


HOST
PORT
INTERNAL_HOST

SCRIPT_NAME=/label-studio \
&& FORCE_SCRIPT_NAME=/label-studio \
&& label-studio


{
	order replace after encode
}


replace [stream | [re] <search> <replace>] {
	stream
	[re] <search> <replace>
}
replace Foo Bar
replace re "\s+foo(bar|baz)\s+" " foo $1 "



##########################################################################################333
{
	order replace after encode
}

:80 {

    redir /label-studio /label-studio/
    route /label-studio/* {
        uri strip_prefix /label-studio
        # this is hacky (let's hope this doesn't randomly break):
        # - label-studio doesn't support a relative subpath (or even absolute subpath w/o hostname)
        # - go regex doesn't support negative lookbehinds, wtf...
        # - we don't know if/when ls will add new static root paths - that will break this
        replace {

            re href="/(label-studio/)?  href="/label-studio/
            re src="/(label-studio/)?   src="/label-studio/
            re img="/(label-studio/)?   img="/label-studio/
            re action="/(label-studio/)? action="/label-studio/
            re next=/(label-studio/)? next=/label-studio/
            re src="/static   src="/label-studio/static
            #src="/
            #re "(?i)(?:label-studio/)?static"                  label-studio/static
            #re "(?i)(?:label-studio/)?user"                    label-studio/user
            #static                  label-studio/static
            #react-app               label-studio/react-app
            #data/upload             label-studio/data/upload    
            #data/avatars            label-studio/data/avatars
            #label-studio-frontend   label-studio/label-studio-frontend         

        }

        reverse_proxy {
            to 127.0.0.1:8081
            header_down  Location (https?://)([^/]+)/(label-studio/)?           $2$3/label-studio/
            header_down  Location ^/(label-studio/)?                            /label-studio/
            header_up    Access-Control-Allow-Origin '*'
            # header_down  Location (?:^.+://)?(?:[^:/]+)?(?::[^/]+)?/(static.*)  /label-studio/$4
            # header_down  Location (?:^.+://)?(?:[^:/]+)?(?::[^/]+)?/user/       /label-studio/user/
            #header_up X-Forwarded-Prefix /label-studio
            #header_up X-Script-Name      /label-studio
            #header_down  Location (?:^.+://)?(?:[^:/]+)?(?::[^/]+)?/(static/.*)  /label-studio/$4
            #header_down  Location (?:^.+://)?(?:[^:/]+)?(?::[^/]+)?/(.*)         /label-studio/$4
            #header_down  Location (?:^.+://)?(?:[^:/]+)?(?::[^/]+)?/user/    /label-studio/user/ 

            #replace re "static(.*)"  "label-studio$1"
            #header_down  Location (?:^.+://)?(?:[^:/]+)?(?::[^/]+)?/  ./
        }

        replace {
            static                  label-studio/static
            react-app               label-studio/react-app
            data/upload             label-studio/data/upload    
            data/avatars            label-studio/data/avatars
            label-studio-frontend   label-studio/label-studio-frontend
        }
        
        replace {
            re href="/(label-studio/)?  href="/label-studio/ 
            re src="/(label-studio/)?   src="/label-studio/
            react-app               label-studio/react-app
            data/upload             label-studio/data/upload    
            data/avatars            label-studio/data/avatars
            label-studio-frontend   label-studio/label-studio-frontend         
        }

    }
}

$(pip show label-studio | grep Location | sed -E "s|^\s*Location:\s*||g" )

    location /label-studio/data/upload {
        alias /label-studio/data/media/upload/;
    }

    location /label-studio/data/avatars {
        alias /label-studio/data/media/avatars;
    }

    location /label-studio/static {
        alias /label-studio/label_studio/core/static_build/;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location /label-studio/label-studio-frontend {
        alias /label-studio/label_studio/frontend/dist/lsf;
    }

    location /label-studio/react-app {
        alias /label-studio/label_studio/frontend/dist/react-app;
    }



##########################################################################################333




git clone https://github.com/heartexlabs/label-studio.git
cd label-studio
python -m venv venv && source venv/bin/activate
nano 
# Install all package dependencies
pip install -e .
# Run database migrations
python label_studio/manage.py migrate
# Start the server in development mode at http://localhost:8080
python label_studio/manage.py runserver




https://github.com/heartexlabs/label-studio.git







server {
    listen       80;
    server_name  _;

    proxy_redirect          off;
    proxy_set_header        Host            $host;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    client_body_buffer_size 128k;
    proxy_connect_timeout   90;
    proxy_send_timeout      90;
    proxy_read_timeout      300;
    proxy_buffers           32 4k;

    location / {
        proxy_pass http://app:8080;
        proxy_set_header Host $http_host;
    }

    location /label-studio/data/upload {
        alias /label-studio/data/media/upload/;
    }

    location /label-studio/data/avatars {
        alias /label-studio/data/media/avatars;
    }

    location /label-studio/static {
        alias /label-studio/label_studio/core/static_build/;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location /label-studio/label-studio-frontend {
        alias /label-studio/label_studio/frontend/dist/lsf;
    }

    location /label-studio/react-app {
        alias /label-studio/label_studio/frontend/dist/react-app;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}














































