#!/bin/bash


docker run --name cloudbeaver --rm -tid -p 8978:8978 dbeaver/cloudbeaver:latest

# https://cloudbeaver.io/docs/Server-configuration/

CB_SERVER_NAME="cloudbeaver"
CB_SERVER_URL="./cloudbeaver/"
CB_ADMIN_NAME="admin"
CB_ADMIN_PASSWORD="password"
#CLOUDBEAVER_HOME="/path/to/server/cloubeaver/root"

--web-config="/etc/cloudbeaver/cloudbeaver.conf"

cloudbeaver.conf
{
    server: {
        serverPort: 8978,
        serverName: "CloudBeaver",

        // Paths are absolute or relative to the server root folder
        workspaceLocation: "workspace",
        contentRoot: "web",
        driversLocation: "drivers",

        rootURI: "/cloudbeaver/",
        serviceURI: "/cloudbeaver/api/",

        // Webapp configuration file
        productConfiguration: "conf/product.conf",

        expireSessionAfterPeriod: 600000,

        develMode: false
    },
    app: {
        anonymousAccessAllowed: true,
        anonymousUserRole: "admin"
    }

}


product.conf

{
    "core": {
        "user": {
            "defaultTheme": "dark"
        }
    }
 "plugin_data_export": {
    "disabled": false
 }
}


# Detect host machine IP Address (we need this when run in docker container)
export CB_LOCAL_HOST_ADDR=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)

docker run --name cloudbeaver --rm -ti -p 8978:8978 --add-host=host.docker.internal:${CB_LOCAL_HOST_ADDR} -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace dbeaver/cloudbeaver:dev
